# Generated by Django 5.0 on 2023-12-25 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrepot', '0001_initial'),
        ('gestionCentre', '0002_employe'),
        ('utilisateur', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiviteDuCentre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('centre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionCentre.centre')),
                ('employe_responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestionCentre.employe')),
            ],
        ),
        migrations.CreateModel(
            name='AnalyseVentes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taux_evolution_ventes', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('taux_evolution_benefice', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('produits_best_seller', models.ManyToManyField(blank=True, to='entrepot.produit')),
                ('top_clients', models.ManyToManyField(blank=True, to='utilisateur.client')),
            ],
        ),
        migrations.CreateModel(
            name='GestionDesEmployes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salaires_journaliers', models.DecimalField(decimal_places=2, max_digits=8)),
                ('absences', models.IntegerField(default=0)),
                ('avances_salaire', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionCentre.employe')),
            ],
        ),
    ]
