# Generated by Django 5.0 on 2024-01-03 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionCentre', '0004_employe_date_gestiondesemployes_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employe',
            name='date',
        ),
    ]
