# Generated by Django 5.0 on 2024-01-03 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionCentre', '0005_remove_employe_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gestiondesemployes',
            name='avances_salaire',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True),
        ),
    ]
