# Generated by Django 5.0 on 2024-01-03 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionCentre', '0006_alter_gestiondesemployes_avances_salaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gestiondesemployes',
            name='salaires_journaliers',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.CreateModel(
            name='PV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_verse', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField(auto_now_add=True)),
                ('description', models.TextField()),
                ('centre_responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionCentre.centre')),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionCentre.employe')),
            ],
        ),
        migrations.DeleteModel(
            name='AnalyseVentes',
        ),
    ]
