# Generated by Django 5.0 on 2024-01-05 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrepot', '0007_stockmanager'),
        ('gestionCentre', '0007_alter_gestiondesemployes_salaires_journaliers_pv_and_more'),
        ('utilisateur', '0005_remove_client_nombre_vente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CentreEtatStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField(default=0)),
                ('date_achat', models.DateField(auto_now_add=True)),
                ('centre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionCentre.centre')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrepot.produit')),
            ],
        ),
        migrations.CreateModel(
            name='CentreVente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField()),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('montant_encaisse', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('date_vente', models.DateField(auto_now_add=True)),
                ('paiement_partiel', models.BooleanField(default=False)),
                ('centre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionCentre.centre')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilisateur.client')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrepot.produit')),
            ],
        ),
    ]
