# Generated by Django 5.0 on 2024-01-05 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrepot', '0007_stockmanager'),
        ('gestionCentre', '0008_centreetatstock_centrevente'),
    ]

    operations = [
        migrations.AddField(
            model_name='centreetatstock',
            name='fournisseur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='entrepot.fournisseur'),
        ),
    ]
