# Generated by Django 5.0 on 2023-12-29 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0002_client_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='credit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
