# Generated by Django 5.0 on 2023-12-30 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0003_alter_client_credit'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='nombre_vente',
            field=models.IntegerField(default=0),
        ),
    ]
