# Generated by Django 5.0 on 2023-12-30 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0004_client_nombre_vente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='nombre_vente',
        ),
        migrations.AddField(
            model_name='client',
            name='prix_total_depense_par_client',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
