# Generated by Django 5.0 on 2024-01-09 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0005_remove_client_nombre_vente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='user',
        ),
    ]
