# Generated by Django 5.0 on 2023-12-25 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entrepot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etatstock',
            name='fournisseur',
        ),
    ]
