# Generated by Django 5.0 on 2023-12-29 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrepot', '0002_remove_etatstock_fournisseur'),
    ]

    operations = [
        migrations.AddField(
            model_name='etatstock',
            name='fournisseur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='entrepot.fournisseur'),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='solde',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
