# Generated by Django 5.0 on 2023-12-29 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entrepot', '0003_etatstock_fournisseur_alter_fournisseur_solde'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='fournisseur',
        ),
    ]
