# Generated by Django 5.0 on 2023-12-30 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrepot', '0004_remove_produit_fournisseur'),
    ]

    operations = [
        migrations.AddField(
            model_name='fournisseur',
            name='nombre_achat',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='produit',
            name='nombre_vente',
            field=models.IntegerField(default=0),
        ),
    ]
