# Generated by Django 5.0 on 2023-12-30 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrepot', '0005_fournisseur_nombre_achat_produit_nombre_vente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fournisseur',
            name='nombre_achat',
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='prix_total_depense_chez_fournisseur',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
