# Generated by Django 5.0 on 2024-01-01 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrepot', '0006_remove_fournisseur_nombre_achat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
