# Generated by Django 5.0 on 2024-01-05 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrepot', '0007_stockmanager'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='nombre_vente_centre',
            field=models.IntegerField(default=0),
        ),
    ]
