# Generated by Django 5.0 on 2024-01-06 01:47

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrepot', '0009_remove_produit_nombre_vente_centre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='nombre_vente',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), size=4),
        ),
    ]
