# Generated by Django 5.0 on 2024-01-06 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrepot', '0010_alter_produit_nombre_vente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='nombre_vente',
        ),
        migrations.AddField(
            model_name='produit',
            name='nombre_vente0',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='produit',
            name='nombre_vente1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='produit',
            name='nombre_vente2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='produit',
            name='nombre_vente3',
            field=models.IntegerField(default=0),
        ),
    ]
